interface EmailRequest {
  to_email: string;
  to_name: string;
  subject: string;
  message: string;
}

interface EmailResponse {
  success: boolean;
  message?: string;
  error?: string;
  messageId?: string;
}

// Determine email backend URL based on environment
const getEmailBackendUrl = (): string => {
  // If explicitly set in env, use it
  if (import.meta.env.VITE_EMAIL_BACKEND_URL) {
    return import.meta.env.VITE_EMAIL_BACKEND_URL;
  }
  
  // For local development, use localhost backend
  if (import.meta.env.DEV) {
    return 'http://localhost:3001';
  }
  
  // For production on GitHub Pages, use Resend API directly
  return 'https://api.resend.com';
};

const EMAIL_BACKEND_URL = getEmailBackendUrl();

export const sendItineraryEmail = async (emailData: EmailRequest): Promise<EmailResponse> => {
  try {
    console.log('📧 Sending itinerary email...');
    console.log('To:', emailData.to_email);

    // For production (GitHub Pages), use Resend API directly
    if (!import.meta.env.DEV && EMAIL_BACKEND_URL === 'https://api.resend.com') {
      const resendApiKey = import.meta.env.VITE_RESEND_API_KEY;
      if (!resendApiKey) {
        throw new Error('Resend API key not configured');
      }

      const response = await fetch('https://api.resend.com/emails', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${resendApiKey}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          from: 'TravelHelperAI <onboarding@resend.dev>',
          to: emailData.to_email,
          subject: emailData.subject,
          html: formatEmailHTML(emailData.to_name, emailData.message),
        }),
      });

      const result = await response.json();

      if (!response.ok) {
        console.error('❌ Email sending failed:', result);
        throw new Error(result.message || 'Failed to send email');
      }

      console.log('✅ Email sent successfully!');
      return {
        success: true,
        message: `Email sent successfully to ${emailData.to_email}`,
        messageId: result.id,
      };
    }

    // For local development, use backend
    const response = await fetch(`${EMAIL_BACKEND_URL}/send-email`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(emailData),
    });

    const result: EmailResponse = await response.json();

    if (!response.ok) {
      console.error('❌ Email sending failed:', result.error);
      throw new Error(result.error || 'Failed to send email');
    }

    console.log('✅ Email sent successfully!');
    return result;
  } catch (error) {
    console.error('❌ Email service error:', error);

    if (error instanceof Error) {
      if (error.message.includes('Failed to fetch')) {
        throw new Error('Email backend is not running. Please start it with: cd email-backend && npm install && npm start');
      }
      throw error;
    }

    throw new Error('Failed to send email');
  }
};

export const checkEmailBackend = async (): Promise<boolean> => {
  try {
    const response = await fetch(`${EMAIL_BACKEND_URL}/health`);
    return response.ok;
  } catch {
    return false;
  }
};

function formatEmailHTML(name: string, message: string): string {
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <style>
        body {
          font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
          line-height: 1.6;
          color: #333;
          background-color: #f5f5f5;
        }
        .container {
          max-width: 600px;
          margin: 0 auto;
          background-color: #ffffff;
          padding: 40px;
          border-radius: 8px;
          box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
        .header {
          background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
          color: white;
          padding: 20px;
          border-radius: 8px;
          margin-bottom: 30px;
          text-align: center;
        }
        .header h1 {
          margin: 0;
          font-size: 28px;
        }
        .content {
          margin: 20px 0;
          white-space: pre-wrap;
          word-wrap: break-word;
        }
        .footer {
          margin-top: 30px;
          padding-top: 20px;
          border-top: 1px solid #eee;
          text-align: center;
          color: #666;
          font-size: 12px;
        }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h1>🌍 Your Travel Itinerary</h1>
          <p>Personalized travel plan from TravelHelperAI</p>
        </div>
        
        <p>Dear ${name},</p>
        
        <div class="content">
${message}
        </div>
        
        <div class="footer">
          <p>Generated by TravelHelperAI - Your AI Travel Planning Assistant</p>
          <p>© 2024 TravelHelperAI. All rights reserved.</p>
        </div>
      </div>
    </body>
    </html>
  `;
}
