import { useState } from 'react';
import './TravelResults.css';

interface FormData {
  destination: string;
  departureCity: string;
  departureDate: string;
  returnDate: string;
  currency: string;
  flightBudget: string;
  accomBudget: string;
  people: string;
  preferences: string;
  directFlights: boolean;
  rentCar: boolean;
  itinerary?: string;
  error?: string;
}

interface TravelResultsProps {
  data: FormData;
}

export default function TravelResults({ data }: TravelResultsProps) {
  const [emailSending, setEmailSending] = useState(false);
  const [emailSent, setEmailSent] = useState(false);
  const [showEmailForm, setShowEmailForm] = useState(false);
  const [emailData, setEmailData] = useState({
    to_email: '',
    to_name: '',
  });

  const calcNights = () => {
    if (!data.departureDate || !data.returnDate) return null;
    const diff = (new Date(data.returnDate).getTime() - new Date(data.departureDate).getTime()) / (1000 * 60 * 60 * 24);
    return diff > 0 ? diff : null;
  };

  const formatDate = (dateStr: string) => {
    if (!dateStr) return 'Not specified';
    const d = new Date(dateStr);
    return d.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  };

  const tripSuggestions = () => {
    return [
      `Explore ${data.destination} at your own pace`,
      'Check local events during your stay',
      'Ask locals for hidden gems',
      'Visit popular attractions and landmarks',
      'Try local restaurants and cuisine',
    ];
  };

  const nights = calcNights();
  const totalAccom =
    nights && data.accomBudget
      ? `${data.currency} ${(nights * Number(data.accomBudget) * Number(data.people)).toLocaleString()}`
      : null;
  const totalBudget =
    data.flightBudget && totalAccom
      ? `${data.currency} ${(Number(data.flightBudget) + nights! * Number(data.accomBudget) * Number(data.people)).toLocaleString()}`
      : null;

  const suggestions = tripSuggestions();

  const handleEmailShare = async (e: React.FormEvent) => {
    e.preventDefault();
    setEmailSending(true);

    try {
      // Create email content
      const emailContent = `
Dear ${emailData.to_name},

Here's your personalized travel itinerary for ${data.destination}!

🌍 TRIP SUMMARY
• Destination: ${data.destination}
• Departure: ${data.departureCity}
• Dates: ${formatDate(data.departureDate)} - ${formatDate(data.returnDate)}
• Travelers: ${data.people} ${Number(data.people) === 1 ? 'person' : 'people'}
• Preferences: ${data.preferences || 'Not specified'}

💰 BUDGET ESTIMATE
${data.flightBudget ? `• Flights: ${data.currency} ${Number(data.flightBudget).toLocaleString()}` : ''}
${data.accomBudget ? `• Accommodation: ${data.currency} ${data.accomBudget}/night per person` : ''}
${totalBudget ? `• Total Estimated Budget: ${totalBudget}` : ''}

${data.itinerary ? `🗓️ AI-GENERATED ITINERARY\n${data.itinerary}` : ''}

✈️ NEXT STEPS
• Search flights: ${data.departureCity} → ${data.destination}${data.directFlights ? ' (direct flights only)' : ''}
• Book accommodation within your budget
${data.rentCar ? '• Arrange car rental at destination\n' : ''}• Check visa requirements
• Consider travel insurance

🔗 USEFUL LINKS
• Flights: https://www.google.com/flights?q=${encodeURIComponent(data.departureCity + ' to ' + data.destination)}
• Hotels: https://www.booking.com/searchresults.html?ss=${encodeURIComponent(data.destination)}
• Activities: https://www.tripadvisor.com/Search?q=${encodeURIComponent(data.destination)}

Happy travels!
Generated by TravelHelperAI
      `;

      // For demo purposes, show email content in console
      console.log('Email content that would be sent:', emailContent);
      
      // Open email preview in new window
      const emailWindow = window.open('', '_blank', 'width=800,height=600,scrollbars=yes');
      if (emailWindow) {
        emailWindow.document.write(`
          <!DOCTYPE html>
          <html>
          <head>
            <title>Email Preview - ${data.destination} Itinerary</title>
            <style>
              body { 
                font-family: Arial, sans-serif; 
                max-width: 800px; 
                margin: 20px auto; 
                padding: 20px;
                line-height: 1.6;
              }
              .header { 
                background: #f0f9ff; 
                padding: 20px; 
                border-radius: 8px; 
                margin-bottom: 20px;
                border-left: 4px solid #3b82f6;
              }
              .content { 
                white-space: pre-wrap; 
                background: #fafafa; 
                padding: 20px; 
                border-radius: 8px;
              }
            </style>
          </head>
          <body>
            <div class="header">
              <h2>📧 Travel Itinerary Email Preview</h2>
              <p><strong>To:</strong> ${emailData.to_email}</p>
              <p><strong>Subject:</strong> Your Travel Itinerary for ${data.destination}</p>
            </div>
            <div class="content">${emailContent.replace(/\n/g, '<br>')}</div>
          </body>
          </html>
        `);
        emailWindow.document.close();
      }

      setEmailSent(true);
      setShowEmailForm(false);
      setTimeout(() => setEmailSent(false), 5000);
    } catch (error) {
      console.error('Email sending failed:', error);
      alert('Failed to send email. Please try again.');
    } finally {
      setEmailSending(false);
    }
  };

  const handleEmailInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setEmailData({
      ...emailData,
      [e.target.name]: e.target.value,
    });
  };

  return (
    <div className="card results">
      <h2>Your Travel Plan</h2>

      {data.error && (
        <div className="result-section error">
          <h3>Error</h3>
          <p>{data.error}</p>
        </div>
      )}

      <div className="result-section">
        <h3>Trip Summary</h3>
        <p>
          <strong>{data.people} {Number(data.people) === 1 ? 'traveller' : 'travellers'}</strong>
          {' '}flying from <strong>{data.departureCity}</strong> to <strong>{data.destination}</strong>
          {data.departureDate && ` on ${formatDate(data.departureDate)}`}
          {data.returnDate && `, returning ${formatDate(data.returnDate)}`}
          {nights && ` (${nights} night${nights !== 1 ? 's' : ''})`}.
        </p>
        <div className="tag-row" style={{ marginTop: '12px' }}>
          {data.preferences && <span className="tag">✨ {data.preferences.substring(0, 30)}...</span>}
          {data.directFlights && <span className="tag">✈️ Direct flights</span>}
          {data.rentCar && <span className="tag">🚗 Car rental</span>}
        </div>
      </div>

      <div className="result-section">
        <h3>Budget Estimate</h3>
        <p>
          {data.flightBudget && (
            <>
              Flights: <strong>{data.currency} {Number(data.flightBudget).toLocaleString()}</strong> total
              <br />
            </>
          )}
          {data.accomBudget && (
            <>
              Accommodation: <strong>{data.currency} {data.accomBudget}/night</strong> per person
              {totalAccom && ` → ${totalAccom}`}
              <br />
            </>
          )}
          {totalBudget ? (
            <>
              Estimated total: <strong>{totalBudget}</strong>
            </>
          ) : (
            !data.flightBudget &&
            !data.accomBudget && (
              'No budget entered — add flight and accommodation budgets for an estimate.'
            )
          )}
        </p>
      </div>

      {data.itinerary && (
        <div className="result-section itinerary-section">
          <h3>AI-Generated Itinerary</h3>
          <div className="itinerary-content">
            {data.itinerary.split('\n').map((line, idx) => (
              <p key={idx}>{line}</p>
            ))}
          </div>
        </div>
      )}

      <div className="result-section">
        <h3>Suggested Activities</h3>
        <ul>
          {suggestions.map((s, idx) => (
            <li key={idx}>{s}</li>
          ))}
        </ul>
      </div>

      <div className="result-section">
        <h3>Next Steps</h3>
        <ul>
          <li>
            Search flights from <strong>{data.departureCity}</strong> to <strong>{data.destination}</strong>
            {data.directFlights && ' (direct only)'}
          </li>
          <li>Compare accommodation options within your budget</li>
          {data.rentCar && <li>Book a rental car at your destination</li>}
          <li>Check visa requirements for your nationality</li>
          <li>Look into travel insurance for your trip</li>
        </ul>
      </div>

      {/* Email Sharing Section */}
      <div className="result-section email-section">
        <h3>Share Your Itinerary</h3>
        {!showEmailForm ? (
          <div className="email-actions">
            <button 
              className="btn-email" 
              onClick={() => setShowEmailForm(true)}
              disabled={emailSending}
            >
              📧 Email This Itinerary
            </button>
            <p className="email-hint">Send detailed travel plan with hotel and flight links</p>
          </div>
        ) : (
          <form className="email-form" onSubmit={handleEmailShare}>
            <div className="email-inputs">
              <input
                type="text"
                name="to_name"
                placeholder="Recipient's name"
                value={emailData.to_name}
                onChange={handleEmailInputChange}
                required
              />
              <input
                type="email"
                name="to_email"
                placeholder="Recipient's email"
                value={emailData.to_email}
                onChange={handleEmailInputChange}
                required
              />
            </div>
            <div className="email-buttons">
              <button type="submit" disabled={emailSending} className="btn-send">
                {emailSending ? '📤 Sending...' : '📧 Send Email'}
              </button>
              <button 
                type="button" 
                onClick={() => setShowEmailForm(false)}
                className="btn-cancel"
              >
                Cancel
              </button>
            </div>
          </form>
        )}
        
        {emailSent && (
          <div className="email-success">
            ✅ Email sent successfully to {emailData.to_email}!
          </div>
        )}
      </div>
    </div>
  );
}
