// Mapping of countries to their currencies
export const countryToCurrency: Record<string, string> = {
  // Europe
  'france': 'EUR',
  'paris': 'EUR',
  'germany': 'EUR',
  'berlin': 'EUR',
  'italy': 'EUR',
  'rome': 'EUR',
  'spain': 'EUR',
  'madrid': 'EUR',
  'barcelona': 'EUR',
  'portugal': 'EUR',
  'lisbon': 'EUR',
  'greece': 'EUR',
  'athens': 'EUR',
  'netherlands': 'EUR',
  'amsterdam': 'EUR',
  'belgium': 'EUR',
  'brussels': 'EUR',
  'austria': 'EUR',
  'vienna': 'EUR',
  'switzerland': 'CHF',
  'zurich': 'CHF',
  'geneva': 'CHF',
  'sweden': 'SEK',
  'stockholm': 'SEK',
  'norway': 'NOK',
  'oslo': 'NOK',
  'denmark': 'DKK',
  'copenhagen': 'DKK',
  'poland': 'PLN',
  'warsaw': 'PLN',
  'czech republic': 'CZK',
  'prague': 'CZK',
  'hungary': 'HUF',
  'budapest': 'HUF',
  'romania': 'RON',
  'bucharest': 'RON',
  'ukraine': 'UAH',
  'kyiv': 'UAH',
  'russia': 'RUB',
  'moscow': 'RUB',
  'uk': 'GBP',
  'united kingdom': 'GBP',
  'london': 'GBP',
  'england': 'GBP',
  'scotland': 'GBP',
  'ireland': 'EUR',
  'dublin': 'EUR',

  // Asia
  'japan': 'JPY',
  'tokyo': 'JPY',
  'kyoto': 'JPY',
  'osaka': 'JPY',
  'china': 'CNY',
  'beijing': 'CNY',
  'shanghai': 'CNY',
  'india': 'INR',
  'delhi': 'INR',
  'new delhi': 'INR',
  'mumbai': 'INR',
  'kolkata': 'INR',
  'bangalore': 'INR',
  'bengaluru': 'INR',
  'hyderabad': 'INR',
  'goa': 'INR',
  'jaipur': 'INR',
  'lucknow': 'INR',
  'kanpur': 'INR',
  'nagpur': 'INR',
  'indore': 'INR',
  'thane': 'INR',
  'pune': 'INR',
  'ahmedabad': 'INR',
  'surat': 'INR',
  'vadodara': 'INR',
  'rajkot': 'INR',
  'chandigarh': 'INR',
  'amritsar': 'INR',
  'ludhiana': 'INR',
  'kochi': 'INR',
  'thiruvananthapuram': 'INR',
  'coimbatore': 'INR',
  'madurai': 'INR',
  'salem': 'INR',
  'visakhapatnam': 'INR',
  'vijayawada': 'INR',
  'guwahati': 'INR',
  'bhopal': 'INR',
  'jabalpur': 'INR',
  'raipur': 'INR',
  'ranchi': 'INR',
  'patna': 'INR',
  'varanasi': 'INR',
  'agra': 'INR',
  'mathura': 'INR',
  'udaipur': 'INR',
  'jodhpur': 'INR',
  'bikaner': 'INR',
  'ajmer': 'INR',
  'pushkar': 'INR',
  'shimla': 'INR',
  'manali': 'INR',
  'dharamshala': 'INR',
  'mussoorie': 'INR',
  'nainital': 'INR',
  'rishikesh': 'INR',
  'haridwar': 'INR',
  'darjeeling': 'INR',
  'gangtok': 'INR',
  'shillong': 'INR',
  'imphal': 'INR',
  'aizawl': 'INR',
  'kohima': 'INR',
  'itanagar': 'INR',
  'thiruchirapalli': 'INR',
  'erode': 'INR',
  'tiruppur': 'INR',
  'kanyakumari': 'INR',
  'ooty': 'INR',
  'coonoor': 'INR',
  'munnar': 'INR',
  'wayanad': 'INR',
  'alleppey': 'INR',
  'kumarakom': 'INR',
  'thailand': 'THB',
  'bangkok': 'THB',
  'vietnam': 'VND',
  'hanoi': 'VND',
  'ho chi minh': 'VND',
  'south korea': 'KRW',
  'seoul': 'KRW',
  'singapore': 'SGD',
  'malaysia': 'MYR',
  'kuala lumpur': 'MYR',
  'indonesia': 'IDR',
  'bali': 'IDR',
  'jakarta': 'IDR',
  'philippines': 'PHP',
  'manila': 'PHP',
  'cambodia': 'KHR',
  'phnom penh': 'KHR',
  'laos': 'LAK',
  'vientiane': 'LAK',
  'myanmar': 'MMK',
  'yangon': 'MMK',
  'pakistan': 'PKR',
  'karachi': 'PKR',
  'bangladesh': 'BDT',
  'dhaka': 'BDT',
  'sri lanka': 'LKR',
  'colombo': 'LKR',
  'nepal': 'NPR',
  'kathmandu': 'NPR',
  'turkey': 'TRY',
  'istanbul': 'TRY',
  'dubai': 'AED',
  'uae': 'AED',
  'abu dhabi': 'AED',
  'saudi arabia': 'SAR',
  'riyadh': 'SAR',
  'israel': 'ILS',
  'tel aviv': 'ILS',
  'jerusalem': 'ILS',

  // Americas
  'usa': 'USD',
  'united states': 'USD',
  'new york': 'USD',
  'los angeles': 'USD',
  'chicago': 'USD',
  'miami': 'USD',
  'las vegas': 'USD',
  'san francisco': 'USD',
  'canada': 'CAD',
  'toronto': 'CAD',
  'vancouver': 'CAD',
  'mexico': 'MXN',
  'cancun': 'MXN',
  'mexico city': 'MXN',
  'brazil': 'BRL',
  'rio de janeiro': 'BRL',
  'sao paulo': 'BRL',
  'argentina': 'ARS',
  'buenos aires': 'ARS',
  'chile': 'CLP',
  'santiago': 'CLP',
  'peru': 'PEN',
  'lima': 'PEN',
  'colombia': 'COP',
  'bogota': 'COP',
  'venezuela': 'VES',
  'caracas': 'VES',
  'ecuador': 'USD',
  'quito': 'USD',
  'costa rica': 'CRC',
  'san jose': 'CRC',
  'panama': 'PAB',
  'panama city': 'PAB',
  'cuba': 'CUP',
  'havana': 'CUP',
  'dominican republic': 'DOP',
  'santo domingo': 'DOP',
  'jamaica': 'JMD',
  'kingston': 'JMD',

  // Africa
  'egypt': 'EGP',
  'cairo': 'EGP',
  'south africa': 'ZAR',
  'johannesburg': 'ZAR',
  'cape town': 'ZAR',
  'kenya': 'KES',
  'nairobi': 'KES',
  'tanzania': 'TZS',
  'dar es salaam': 'TZS',
  'uganda': 'UGX',
  'kampala': 'UGX',
  'ethiopia': 'ETB',
  'addis ababa': 'ETB',
  'morocco': 'MAD',
  'marrakech': 'MAD',
  'casablanca': 'MAD',
  'tunisia': 'TND',
  'tunis': 'TND',
  'algeria': 'DZD',
  'algiers': 'DZD',
  'nigeria': 'NGN',
  'lagos': 'NGN',
  'ghana': 'GHS',
  'accra': 'GHS',
  'cameroon': 'XAF',
  'yaoundé': 'XAF',
  'ivory coast': 'XOF',
  'abidjan': 'XOF',
  'senegal': 'XOF',
  'dakar': 'XOF',
  'botswana': 'BWP',
  'gaborone': 'BWP',
  'namibia': 'NAD',
  'windhoek': 'NAD',
  'zimbabwe': 'ZWL',
  'harare': 'ZWL',
  'mauritius': 'MUR',
  'port louis': 'MUR',

  // Oceania
  'australia': 'AUD',
  'sydney': 'AUD',
  'melbourne': 'AUD',
  'brisbane': 'AUD',
  'new zealand': 'NZD',
  'auckland': 'NZD',
  'wellington': 'NZD',
  'fiji': 'FJD',
  'suva': 'FJD',
  'samoa': 'WST',
  'apia': 'WST',
  'vanuatu': 'VUV',
  'port vila': 'VUV',
};

export function getCurrencyByDestination(destination: string): string {
  if (!destination) return 'EUR';
  
  const normalized = destination.toLowerCase().trim();
  
  // Direct match
  if (countryToCurrency[normalized]) {
    return countryToCurrency[normalized];
  }
  
  // Partial match - check if any key is contained in the input
  for (const [country, currency] of Object.entries(countryToCurrency)) {
    if (normalized.includes(country)) {
      return currency;
    }
  }
  
  // Reverse partial match - check if input is contained in any key
  for (const [country, currency] of Object.entries(countryToCurrency)) {
    if (country.includes(normalized)) {
      return currency;
    }
  }
  
  // Default to EUR if no match found
  return 'EUR';
}
