const { Resend } = require('resend');

const resend = new Resend(process.env.RESEND_API_KEY);

module.exports = async function handler(req, res) {
  // Only allow POST requests
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { to_email, to_name, subject, message } = req.body;

    // Validate input
    if (!to_email || !to_name || !subject || !message) {
      return res.status(400).json({
        success: false,
        error: 'Missing required fields: to_email, to_name, subject, message',
      });
    }

    console.log(`📧 Sending email to: ${to_email}`);

    // Send email via Resend
    const response = await resend.emails.send({
      from: 'TravelHelperAI <onboarding@resend.dev>',
      to: to_email,
      subject: subject,
      html: formatEmailHTML(to_name, message),
    });

    if (response.error) {
      console.error('❌ Email sending failed:', response.error);
      return res.status(500).json({
        success: false,
        error: response.error.message || 'Failed to send email',
      });
    }

    console.log(`✅ Email sent successfully! Message ID: ${response.data?.id}`);

    return res.status(200).json({
      success: true,
      message: `Email sent successfully to ${to_email}`,
      messageId: response.data?.id,
    });
  } catch (error) {
    console.error('❌ Email sending failed:', error);
    return res.status(500).json({
      success: false,
      error: error.message || 'Failed to send email',
    });
  }
};

function formatEmailHTML(name, message) {
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <style>
        body {
          font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
          line-height: 1.6;
          color: #333;
          background-color: #f5f5f5;
        }
        .container {
          max-width: 600px;
          margin: 0 auto;
          background-color: #ffffff;
          padding: 40px;
          border-radius: 8px;
          box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
        .header {
          background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
          color: white;
          padding: 20px;
          border-radius: 8px;
          margin-bottom: 30px;
          text-align: center;
        }
        .header h1 {
          margin: 0;
          font-size: 28px;
        }
        .content {
          margin: 20px 0;
          white-space: pre-wrap;
          word-wrap: break-word;
        }
        .footer {
          margin-top: 30px;
          padding-top: 20px;
          border-top: 1px solid #eee;
          text-align: center;
          color: #666;
          font-size: 12px;
        }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h1>🌍 Your Travel Itinerary</h1>
          <p>Personalized travel plan from TravelHelperAI</p>
        </div>
        
        <p>Dear ${name},</p>
        
        <div class="content">
${message}
        </div>
        
        <div class="footer">
          <p>Generated by TravelHelperAI - Your AI Travel Planning Assistant</p>
          <p>© 2024 TravelHelperAI. All rights reserved.</p>
        </div>
      </div>
    </body>
    </html>
  `;
}
